http://localhost:8000/api/auth/register
### Register a new user
POST http://localhost:8000/api/auth/register
Content-Type: application/json  

{
    "email": "testuser",
    "password": "123456"
}

### Login with existing user
POST http://localhost:8000/api/auth/login
Content-Type: application/json  

{
    "email": "testuser",
    "password": "123456"
}
